spring:
  h2:
    console:
      enabled: true
  datasource:
    # url: jdbc:h2:file:~/data/test
    url: jdbc:h2:mem:test
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  issuer: issuer
  secret: secret
