spring:
  h2:
    console:
      enabled: true
  datasource:
    # url: jdbc:h2:file:~/data/test
    url: jdbc:h2:mem:test
    username: user
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  issuer: issuer
  secret: secret
